### ISSUE TITLE
Fail to train a GCCN with a code example in the README.md file ?

### ISSUE THREAD

**Issue by JieCoa** [geometric-intelligence/TopoBenchmark#123]
When I clone the code to my local environment(Windows) and try to run the code example of "Defining 和 training a GCCN", I get some error and I don't know how to fix it out. Can anyone give me some advise?
![image](https://github.com/user-attachments/assets/b82d5b0d-eb5c-4016-90b1-2c108daa7887)

**Comment by JieCoa** [comment]
And I also fail to reproduce experiments in "[scripts/topotune/existing_models](https://github.com/geometric-intelligence/TopoBenchmark/blob/main/scripts/topotune/existing_models)" with an error "In 'hydra/config': Could not find 'hydra/job_logging/colorlog'" (Is it a problem with my environment configuration?)
![image](https://github.com/user-attachments/assets/d7e84a1f-1c71-418e-bce9-005b77248106)

**Comment by gbg141** [comment]
Hi @JieCoa ! Thanks for reaching out and pointing this out. Actually, the scripts to reproduce TopoTune got outdated after the last changes that we applied to the library.

Our last PR (https://github.com/geometric-intelligence/TopoBenchmark/pull/124) addresses this, and now the scripts are compatible with the current code. For instance, you could run 

`python -m topobenchmark  model=cell/topotune  model.tune_gnn=GCN  model.backbone.GNN.num_layers=1  model.backbone.neighborhoods=\[1-up_incidence-0,1-up_adjacency-1,1-down_incidence-2\]  dataset=graph/MUTAG  optimizer.parameters.lr=0.001  model.feature_encoder.out_channels=128  model.backbone.layers=2  model.readout.readout_name=PropagateSignalDown  model.feature_encoder.proj_dropout=0.25  dataset.dataloader_params.batch_size=32  transforms.graph2cell_lifting.max_cell_length=10  dataset.split_params.data_seed=0,3,5,7,9  trainer.max_epochs=500  trainer.min_epochs=50  trainer.check_val_every_n_epoch=5  callbacks.early_stopping.patience=10 `

Please let us know if you still have some issues reproducing the experiments: probably then it would be related to an environment configuration, and we could take a closer look.

**Comment by JieCoa** [comment]
Thanks for your reply, but I still have some questions about the `model.backbone.neighborhoods`  configuration. I used the script you provided with `--multirun` to test. And I got an unexpected error in the follow image.
![image](https://github.com/user-attachments/assets/039e2c7f-7108-4472-b287-426b47dd5681)

Then I test the script in "Defining and training a GCCN".
`python -m topobenchmark  dataset=graph/PROTEINS  dataset.split_params.data_seed=1  model=cell/topotune  model.tune_gnn=GCN  model.backbone.GNN.num_layers=2  model.backbone.neighborhoods=\[1-up_laplacian-0,1-down_incidence-2\]  model.backbone.layers=4  model.feature_encoder.out_channels=32  model.feature_encoder.proj_dropout=0.3  model.readout.readout_name=PropagateSignalDown  logger.wandb.project=TopoTune_cell  trainer.max_epochs=1000  callbacks.early_stopping.patience=50`
A different but somewhat similar error to the one mentioned above occurred.
![image](https://github.com/user-attachments/assets/31b5b475-dc4f-452e-a53b-e8e9f7d499f4)

I thought the error was related to the `\` symbol in `model.backbone.neighborhoods=\[1-up_laplacian-0,1-down_incidence-2\] `, so I removed all the `\` and then the code ran successfully. 
```shell
python -m topobenchmark  dataset=graph/PROTEINS  dataset.split_params.data_seed=1  model=cell/topotune  model.tune_gnn=GCN  model.backbone.GNN.num_layers=2  model.backbone.neighborhoods=[1-up_laplacian-0,1-down_incidence-2]  model.backbone.layers=4  model.feature_encoder.out_channels=32  model.feature_encoder.proj_dropout=0.3  model.readout.readout_name=PropagateSignalDown  logger.wandb.project=TopoTune_cell  trainer.max_epochs=1000  callbacks.early_stopping.patience=50 
```
![image](https://github.com/user-attachments/assets/0553e5cf-c27d-4fd6-accb-da20d1b4d896)

I don't know what the situation is like in your area, but this is my current situation. If I have misunderstood, I hope to get your reply.
