### ISSUE TITLE
Check Incidence/Hodge Laplacian for TNN architectures 

### ISSUE THREAD

**Issue by JorgeLuizFranco** [geometric-intelligence/TopoBenchmark#125]
I would like to understand, what happens if I use SimplicialComplex(SC) NNs (SCN2 for example) and Cell complex(CC) NNs( CWN for example) within Incidence/Hodge Laplacian matrices  that does not follow the restrictions of these structures( inclusion of coboundaries, etc...).

With some tests, apparently these models keep working even if the matrices you pass for message passing do not represent a SC or even a CC.

If these checks do not exist, these models just do message passing as in an hypergraph?

Or this is in fact an error, and I shouldn't pass a matrix that does not follow the conditions to be a SC or a SC to the architecture and it is a limitation of the code not doing this check?

**Comment by gbg141** [comment]
Hi @JorgeLuizFranco ! Thank you for bringing up this topic.

Indeed, domain-specific TNNs are agnostic of whether the provided neighborhoods follow the corresponding domain restrictions --compatible dimensionalities is all what they need to run. When they do not respect them, an arbitrary,  message passing between cells is executed, but it is not exactly equivalent to hypergraphs given the (non-topological grounded) hierarchical procedure between the cells of different ranks.

In our attempt to deal with this limitation, the default configurations within TopoBenchmark implement resolvers that ensure that the lifted domain coincides with the domain of the selected model. We are currently working on expanding the documentation of the library to better describe how these hydra-based resolvers operate, as well as how to modify the experiment configuration in a way that respects the aforementioned domain constraints.

Hope this answers your questions, and please let us know if you would like to discuss it in more detail.
