### ISSUE TITLE
How to use my own dataset?

### ISSUE THREAD

**Issue by WHSmyself** [geometric-intelligence/TopoBenchmark#91]
Hello, I do not know how to use my own datasets.

**Comment by levtelyatnikov** [comment]
Dear WHSmyself, I am sorry for the late reply. 

We have not officially released the tutorial on how to integrate the custom dataset yet, but we do have an [unofficial one](https://github.com/geometric-intelligence/TopoBenchmark/blob/add_new_dataset_tutorial/tutorials/tutorial_add_own_dataset.ipynb). 
Please let me know if you need any further clarifications.

best, lt
